
using System;
 
public class FigmaScreenNames {

    // Automatically generated by UnityFigmaBridge
          
	public const string REMIX_MODE_SCORE = "REMIX MODE-SCORE";
	public const string REMIX_MODE = "REMIX MODE";
	public const string STAGE_MODE_FAIL="STAGE MODE-FAIL";
	public const string STAGE_MODE_CLEAR="STAGE MODE-CLEAR";
	public const string STAGE_MODE="STAGE MODE";
	public const string SETTINGS_INGAME="SETTINGS-INGAME";
	public const string SETTINGS_MAIN="SETTINGS-MAIN";
	public const string MAIN_REMIX_MODE="MAIN-REMIX MODE";
	public const string MAIN_STAGE_MODE="MAIN-STAGE MODE";
	public const string MAIN="MAIN";

}
